[package]
name = "rocket_mvc"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
rocket_dyn_templates = { version = "0.1", features = ["tera"] }
serde_json = "1.0"
